#
# https://github.com/P3TERX/IBM-CF-V2
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: IBM Cloud Foundry - XRay

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M

on:
  workflow_dispatch:
  repository_dispatch:
#  schedule:
#    - cron: 0 21 * * 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}
      XR_UUID: ${{ secrets.XR_UUID }}
      XR_WS_PATH_VMESS: ${{ secrets.XR_WS_PATH_VMESS }}
      XR_WS_PATH_VLESS: ${{ secrets.XR_WS_PATH_VLESS }}
      SS_PASS: ${{ secrets.SS_PASS }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zxC /tmp
        sudo install -m 755 /tmp/cf7 /usr/local/bin/cf
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Latest XRay
      run: |
        DOWNLOAD_URL="https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "latest-xray.zip"
        unzip latest-xray.zip xray geoip.dat geosite.dat
        rm latest-xray.zip
        chmod -v 755 x*
        ./xray -version
        mv xray ${IBM_CF_APP_NAME}

    - name: Generate XRay Config File (VMess)
#      if: ${{ env.XR_WS_PATH_VMESS }}
      run: |
        base64 << P3TERX > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${XR_UUID}",
                    "alterId": 64
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "${XR_WS_PATH_VMESS}"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        P3TERX

    - name: Generate XRay Config File (VLESS)
      if: ${{ env.XR_WS_PATH_VLESS }}
      run: |
        base64 << P3TERX > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "port": 8080,
              "protocol": "vless",
              "settings": {
                "decryption": "none",
                "clients": [
                  {
                    "id": "${XR_UUID}",
                    "flow": "xtls-rprx-direct",
                    "level": 0,
                    "email": "love@xray.org"
                  }
                ]
              },
              "streamSettings": {
                "network":"tcp",
                "security": "xtls",
                "tcpSettings": {
                 "type": "none"
                },
                "xtlsSettings": {
                   "allowInsecure": false
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        P3TERX

    - name: Generate Manifest File
      run: |
        cat << P3TERX > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config > config.json; ./${IBM_CF_APP_NAME} -config=config.json
          buildpacks:
          - binary_buildpack
        P3TERX

    - name: Deploy Cloud Foundry App
      run: cf push
